# Generated by Django 5.2.6 on 2025-10-30 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0007_alter_packageimage_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('travel_date', models.DateField(help_text='Fecha en que se realizará el tour', verbose_name='Fecha del Viaje')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('REFUNDED', 'Reembolsada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('tickets_detail', models.JSONField(help_text='Cantidad de personas por tipo de ticket', verbose_name='Detalle de Tickets')),
                ('tickets_prices', models.JSONField(help_text='Precio unitario con comisión de cada tipo de ticket', verbose_name='Precios de Tickets')),
                ('selected_extras', models.JSONField(blank=True, null=True, verbose_name='Servicios Extras Seleccionados')),
                ('extras_prices', models.JSONField(blank=True, help_text='Precio con comisión de cada servicio extra', null=True, verbose_name='Precios de Extras')),
                ('subtotal_tickets', models.DecimalField(decimal_places=2, help_text='Suma de todos los tickets', max_digits=10, verbose_name='Subtotal Tickets')),
                ('subtotal_extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todos los extras', max_digits=10, verbose_name='Subtotal Extras')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Precio final que paga el viajero', max_digits=10, verbose_name='Monto Total')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Ganancia de VENTU', max_digits=10, verbose_name='Comisión de Plataforma')),
                ('operator_amount', models.DecimalField(decimal_places=2, help_text='Dinero que recibe el operador (sin comisión)', max_digits=10, verbose_name='Monto del Operador')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión al momento de la reserva', max_digits=5, verbose_name='Tasa de Comisión')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('special_requests', models.TextField(blank=True, help_text='Alergias, dietas, necesidades especiales, etc.', verbose_name='Solicitudes Especiales')),
                ('payment_id', models.CharField(blank=True, help_text='ID de la transacción de la pasarela de pago', max_length=255, verbose_name='ID de Transacción')),
                ('payment_method', models.CharField(blank=True, help_text='Ej: stripe, paypal, transferencia', max_length=50, verbose_name='Método de Pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('booking_code', models.CharField(editable=False, help_text='Código único para identificar la reserva', max_length=10, unique=True, verbose_name='Código de Reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Razón de Cancelación')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tourpackage', verbose_name='Paquete Turístico')),
                ('traveler', models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Viajero')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('REFUNDED', 'Reembolsada')], max_length=20, verbose_name='Estado Anterior')),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('REFUNDED', 'Reembolsada')], max_length=20, verbose_name='Nuevo Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['traveler', 'status'], name='bookings_bo_travele_3a0711_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour_package', 'travel_date'], name='bookings_bo_tour_pa_a4b787_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code'], name='bookings_bo_booking_51e913_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'travel_date'], name='bookings_bo_status_e47cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
    ]
