# Generated by Django 5.2.6 on 2025-10-02 16:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ítem')),
            ],
            options={
                'verbose_name': 'Ítem Incluido',
                'verbose_name_plural': 'Ítems Incluidos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_origin', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], default='Distrito Capital', max_length=50, verbose_name='Estado de Origen')),
                ('specific_origin', models.CharField(default='Por definir', help_text='Ej: Aeropuerto de Maiquetía, Terminal de La Bandera', max_length=150, verbose_name='Lugar Específico de Origen')),
                ('state_destination', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], default='Miranda', max_length=50, verbose_name='Estado de Destino')),
                ('specific_destination', models.CharField(default='Por definir', help_text='Ej: Playa Colorada, Parque Nacional Morrocoy', max_length=150, verbose_name='Destino Específico')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Base')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, verbose_name='Tasa de Comisión')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Precio Final (con comisión)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Aprobación'), ('PUBLISHED', 'Publicado'), ('REJECTED', 'Rechazado')], default='PUBLISHED', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción Larga')),
                ('meeting_point', models.CharField(max_length=255, verbose_name='Lugar de Encuentro')),
                ('meeting_time', models.TimeField(verbose_name='Hora de Encuentro')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duración (días)')),
                ('environment', models.CharField(choices=[('FESTIVE_MUSIC', 'Festivo con Música'), ('RELAXING_NO_MUSIC', 'Relajante sin Música'), ('ADVENTUROUS', 'Aventurero/Extremo'), ('CULTURAL', 'Cultural/Educativo'), ('ROMANTIC', 'Romántico'), ('FAMILY', 'Familiar'), ('LUXURY', 'Lujo/Exclusivo')], default='RELAXING_NO_MUSIC', max_length=50, verbose_name='Entorno/Ambiente')),
                ('group_size', models.PositiveIntegerField(default=10, help_text='Número máximo de participantes', verbose_name='Tamaño Máximo del Grupo')),
                ('highlights', models.JSONField(blank=True, help_text="Lista de puntos destacados, ej: ['Playa privada', 'Buffet incluido', 'Guía bilingüe']", null=True, verbose_name='Puntos Destacados')),
                ('variable_prices', models.JSONField(blank=True, help_text="Ejemplo: {'niños': 50.00, 'tercera_edad': 45.00}", null=True, verbose_name='Precios Adicionales')),
                ('itinerary', models.JSONField(blank=True, help_text="Ejemplo: {'Día 1': 'Salida y llegada...', 'Día 2': 'Excursión...'}", null=True, verbose_name='Itinerario Detallado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Paquete Activo')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es Recurrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to=settings.AUTH_USER_MODEL, verbose_name='Operador Turístico')),
                ('tags', models.ManyToManyField(blank=True, related_name='tour_packages', to='tours.tag', verbose_name='Etiquetas Informativas')),
                ('what_is_included', models.ManyToManyField(blank=True, related_name='packages_included', to='tours.includeditem', verbose_name='Qué Incluye')),
                ('what_is_not_included', models.ManyToManyField(blank=True, related_name='packages_not_included', to='tours.includeditem', verbose_name='Qué No Incluye')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Archivo de Imagen')),
                ('is_main_image', models.BooleanField(default=False, verbose_name='Es Imagen Principal')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage', verbose_name='Paquete Turístico')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5 estrellas)')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traveler', models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Viajero')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tourpackage', verbose_name='Paquete Turístico')),
            ],
            options={
                'unique_together': {('tour_package', 'traveler')},
            },
        ),
    ]
