# Generated by Django 5.2.6 on 2025-09-16 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Archivo de Imagen')),
                ('is_main_image', models.BooleanField(default=False, verbose_name='Es Imagen Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5 estrellas)')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción Larga')),
                ('location', models.CharField(max_length=150, verbose_name='Ubicación (Región/Estado)')),
                ('destination', models.CharField(max_length=150, verbose_name='Destino Específico')),
                ('meeting_point', models.CharField(max_length=255, verbose_name='Lugar de Encuentro')),
                ('meeting_time', models.TimeField(verbose_name='Hora de Encuentro')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duración (días)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base (Adulto)')),
                ('variable_prices', models.JSONField(blank=True, help_text="Ejemplo: {'niños': 50.00, 'tercera_edad': 45.00}", null=True, verbose_name='Precios Adicionales')),
                ('what_is_included', models.JSONField(default=list, help_text="Una lista de strings. Ejemplo: ['Transporte', 'Almuerzo', 'Guía']", verbose_name='Qué Incluye')),
                ('what_is_not_included', models.JSONField(default=list, help_text="Una lista de strings. Ejemplo: ['Bebidas alcohólicas', 'Propinas']", verbose_name='Qué No Incluye')),
                ('itinerary', models.JSONField(blank=True, help_text="Ejemplo: {'Día 1': 'Salida y llegada...', 'Día 2': 'Excursión...'}", null=True, verbose_name='Itinerario Detallado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Paquete Activo')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es Recurrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'ordering': ['-created_at'],
            },
        ),
    ]
