# Generated by Django 5.2.6 on 2025-10-07 20:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio mínimo: $1.00', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='environment',
            field=models.CharField(choices=[('Festivo con Música', 'Festive Music'), ('Relajante sin Música', 'Relaxing No Music'), ('Aventurero/Extremo', 'Adventurous'), ('Cultural/Educativo', 'Cultural'), ('Romántico', 'Romantic'), ('Familiar', 'Family'), ('Lujo/Exclusivo', 'Luxury')], default='Relajante sin Música', max_length=50, verbose_name='Entorno/Ambiente'),
        ),
    ]
