# Generated by Django 5.2.6 on 2025-09-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='traveler',
            field=models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Viajero'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to=settings.AUTH_USER_MODEL, verbose_name='Operador Turístico'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='tours.tag', verbose_name='Etiquetas Informativas'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tourpackage', verbose_name='Paquete Turístico'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage', verbose_name='Paquete Turístico'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tour_package', 'traveler')},
        ),
    ]
