# Generated by Django 5.2.6 on 2025-10-29 19:56

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourpackage_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Imagen del Paquete', 'verbose_name_plural': 'Imágenes del Paquete'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AddField(
            model_name='packageimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Leyenda'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Reseña Aprobada'),
        ),
        migrations.AddField(
            model_name='review',
            name='operator_response',
            field=models.TextField(blank=True, verbose_name='Respuesta del Operador'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Reseña sin título', max_length=200, verbose_name='Título de la Reseña'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='availability_type',
            field=models.CharField(choices=[('OPEN_DATES', 'Fechas Abiertas'), ('SPECIFIC_DATE', 'Fecha Específica')], default='OPEN_DATES', max_length=20, verbose_name='Tipo de Disponibilidad'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='available_from',
            field=models.DateField(blank=True, help_text='Fecha de inicio del rango de disponibilidad', null=True, verbose_name='Disponible Desde'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='available_until',
            field=models.DateField(blank=True, help_text='Fecha de fin del rango de disponibilidad', null=True, verbose_name='Disponible Hasta'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='current_bookings',
            field=models.PositiveIntegerField(default=0, help_text='Número de plazas reservadas', verbose_name='Reservas Actuales'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Fecha específica de salida del tour', null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Hora específica de salida', null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de participantes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad Máxima'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='tour_packages/%Y/%m/%d/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio base antes de comisiones', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'), message='El precio debe ser al menos $1.00')], verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'), message='La comisión no puede ser mayor al 100%')], verbose_name='Tasa de Comisión'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='group_size',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de participantes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamaño Máximo del Grupo'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['status', 'is_active'], name='tours_tourp_status_ea83de_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['state_destination'], name='tours_tourp_state_d_37be30_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['availability_type', 'departure_date'], name='tours_tourp_availab_cd416b_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['operator', 'created_at'], name='tours_tourp_operato_1b7394_idx'),
        ),
    ]
