# Generated by Django 5.2.6 on 2025-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ítem')),
            ],
            options={
                'verbose_name': 'Ítem Incluido',
                'verbose_name_plural': 'Ítems Incluidos',
            },
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='what_is_included',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='what_is_not_included',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='what_is_included',
            field=models.ManyToManyField(blank=True, related_name='packages_included', to='tours.includeditem', verbose_name='Qué Incluye'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='what_is_not_included',
            field=models.ManyToManyField(blank=True, related_name='packages_not_included', to='tours.includeditem', verbose_name='Qué No Incluye'),
        ),
    ]
