# Generated by Django 5.2.6 on 2025-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_packageimage_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='environment',
            field=models.CharField(choices=[('FESTIVE_MUSIC', '🎉 Festivo con Música'), ('RELAXING_NO_MUSIC', '😌 Relajante sin Música'), ('ADVENTUROUS', '🧗 Aventurero/Extremo'), ('CULTURAL', '🏛️ Cultural/Educativo'), ('ROMANTIC', '💝 Romántico'), ('FAMILY', '👨\u200d👩\u200d👧\u200d👦 Familiar'), ('LUXURY', '🌟 Lujo/Exclusivo'), ('NATURE', '🌳 Naturaleza'), ('BEACH', '🏖️ Playa'), ('MOUNTAIN', '⛰️ Montaña'), ('HISTORICAL', '🏺 Histórico'), ('GASTRONOMIC', '🍴 Gastronómico'), ('WELLNESS', '💆 Wellness')], default='RELAXING_NO_MUSIC', max_length=50, verbose_name='Entorno/Ambiente'),
        ),
    ]
