# Generated by Django 5.2.6 on 2025-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_includeditem_remove_tourpackage_what_is_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Tasa de Comisión'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Aprobación'), ('PUBLISHED', 'Publicado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20),
        ),
    ]
