# Generated by Django 5.2.6 on 2025-09-29 15:29
from django.db import migrations

def populate_base_price(apps, schema_editor):
    TourPackage = apps.get_model('tours', 'TourPackage')
    for package in TourPackage.objects.all():
        if package.base_price is None:
            package.base_price = package.price
            package.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourpackage_base_price_tourpackage_commission_rate_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_base_price),
    ]