# Generated by Django 5.2.6 on 2025-10-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourpackage_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='max_capacity',
        ),
    ]
