# Generated by Django 5.2.6 on 2025-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tourpackage_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='variable_prices',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='extra_services',
            field=models.JSONField(blank=True, help_text="Ejemplo: {'comidas': 40.00, 'seguro_viaje': 30.00}", null=True, verbose_name='Servicios Adicionales'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_variations',
            field=models.JSONField(blank=True, help_text="Ejemplo: {'adulto': 100.00, 'niño': 50.00, 'tercera_edad': 70.00}", null=True, verbose_name='Variaciones de Precio'),
        ),
    ]
