# Generated by Django 5.2.6 on 2025-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_populate_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='price',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base'),
        ),
    ]
