# Generated by Django 5.2.6 on 2025-10-30 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourpackage_variable_prices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='extra_services_with_commission',
            field=models.JSONField(blank=True, editable=False, help_text='Calculado automáticamente aplicando commission_rate', null=True, verbose_name='Servicios Adicionales (con comisión)'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_variations_with_commission',
            field=models.JSONField(blank=True, editable=False, help_text='Calculado automáticamente aplicando commission_rate', null=True, verbose_name='Variaciones de Precio (con comisión)'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='tour_packages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='operator_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='Reseña sin título', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tourpackage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='traveler',
            field=models.ForeignKey(limit_choices_to={'role': 'TRAVELER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio neto antes de aplicar comisión de plataforma', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Precio Base (sin comisión)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Comisión de la plataforma (0.10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Tasa de Comisión (%)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='current_bookings',
            field=models.PositiveIntegerField(default=0, verbose_name='Reservas Actuales'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='environment',
            field=models.CharField(choices=[('FESTIVE_MUSIC', '🎉 Festivo con Música'), ('RELAXING_NO_MUSIC', '😌 Relajante sin Música'), ('ADVENTUROUS', '🧗 Aventurero/Extremo'), ('CULTURAL', '🏛️ Cultural/Educativo'), ('ROMANTIC', '💑 Romántico'), ('FAMILY', '👨\u200d👩\u200d👧\u200d👦 Familiar'), ('LUXURY', '🌟 Lujo/Exclusivo'), ('NATURE', '🌳 Naturaleza'), ('BEACH', '🏖️ Playa'), ('MOUNTAIN', '⛰️ Montaña'), ('HISTORICAL', '🏺 Histórico'), ('GASTRONOMIC', '🍴 Gastronómico'), ('WELLNESS', '💆 Wellness')], default='RELAXING_NO_MUSIC', max_length=50, verbose_name='Entorno/Ambiente'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='extra_services',
            field=models.JSONField(blank=True, help_text='Precios netos. Ej: {"comidas": 40.00, "seguro": 30.00}', null=True, verbose_name='Servicios Adicionales (sin comisión)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Calculado automáticamente: base_price * (1 + commission_rate)', max_digits=10, null=True, verbose_name='Precio Final (con comisión)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='group_size',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamaño Máximo del Grupo'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='highlights',
            field=models.JSONField(blank=True, null=True, verbose_name='Puntos Destacados'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Recurrente'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='itinerary',
            field=models.JSONField(blank=True, null=True, verbose_name='Itinerario Detallado'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price_variations',
            field=models.JSONField(blank=True, help_text='Precios netos por tipo. Ej: {"adulto": 100.00, "niño": 50.00}', null=True, verbose_name='Variaciones de Precio (sin comisión)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='specific_destination',
            field=models.CharField(default='Por definir', help_text='Ej: Playa Colorada', max_length=150, verbose_name='Destino Específico'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='specific_origin',
            field=models.CharField(default='Por definir', help_text='Ej: Aeropuerto de Maiquetía', max_length=150, verbose_name='Lugar Específico de Origen'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='tours.tag', verbose_name='Etiquetas'),
        ),
    ]
