# Generated by Django 5.2.6 on 2025-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourpackage_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Aprobación'), ('PUBLISHED', 'Publicado'), ('REJECTED', 'Rechazado')], default='PUBLISHED', max_length=20),
        ),
    ]
