# Generated by Django 5.2.6 on 2025-09-30 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tourpackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, verbose_name='Tasa de Comisión'),
        ),
    ]
