# Generated by Django 5.2.6 on 2025-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tourpackage_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='location',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='environment',
            field=models.CharField(choices=[('FESTIVE_MUSIC', 'Festivo con Música'), ('RELAXING_NO_MUSIC', 'Relajante sin Música'), ('ADVENTUROUS', 'Aventurero/Extremo'), ('CULTURAL', 'Cultural/Educativo'), ('ROMANTIC', 'Romántico'), ('FAMILY', 'Familiar'), ('LUXURY', 'Lujo/Exclusivo')], default='RELAXING_NO_MUSIC', max_length=50, verbose_name='Entorno/Ambiente'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='group_size',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de participantes', verbose_name='Tamaño Máximo del Grupo'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.JSONField(blank=True, help_text="Lista de puntos destacados, ej: ['Playa privada', 'Buffet incluido', 'Guía bilingüe']", null=True, verbose_name='Puntos Destacados'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='specific_destination',
            field=models.CharField(default='Por definir', help_text='Ej: Playa Colorada, Parque Nacional Morrocoy', max_length=150, verbose_name='Destino Específico'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='specific_origin',
            field=models.CharField(default='Por definir', help_text='Ej: Aeropuerto de Maiquetía, Terminal de La Bandera', max_length=150, verbose_name='Lugar Específico de Origen'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='state_destination',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], default='Miranda', max_length=50, verbose_name='Estado de Destino'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='state_origin',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], default='Distrito Capital', max_length=50, verbose_name='Estado de Origen'),
        ),
    ]
