# Generated by Django 5.2.6 on 2025-09-22 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Aprobación'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='rif_type',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico'), ('G', 'Gubernamental')], max_length=1, verbose_name='Tipo de RIF'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operatorprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
