# Generated by Django 5.2.6 on 2025-10-31 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operator_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
